stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  RANCHER_URL_STAGE: http://172.16.1.38:8080/
  RANCHER_URL_PRODUCTION: http://172.16.45.1:8080/

before_script:
  - cp config.js.template config.js

spec:commit:node8:
  image: node:8
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - node_modules
    expire_in: 5d
  script:
    - npm set registry http://172.16.1.29:4873
    - npm install
    - npm test

build:container:tag:
  image: docker:latest
  dependencies:
    - spec:commit:node8
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

build:container:stage:
  image: docker:latest
  dependencies:
    - spec:commit:node8
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:stage .
    - docker push $CI_REGISTRY_IMAGE:stage
  only:
    - develop

build:container:
  image: docker:latest
  dependencies:
    - spec:commit:node8
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy::stage:
  image: wzrdtales/ci-rancher-tools:latest
  dependencies: []
  stage: deploy
  script:
    - cd rancher/stage
    - export RANCHER_URL=$RANCHER_URL_STAGE
    - export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY_STAGE
    - export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY_STAGE
    - rancher-compose -p dfs up --force-upgrade -c --batch-size 1 -d --upgrade --pull
  environment:
    name: stage
  only:
    - develop

deploy::production:
  image: wzrdtales/ci-rancher-tools:latest
  dependencies: []
  stage: deploy
  script:
    - cd rancher/production
    - export RANCHER_URL=$RANCHER_URL_PRODUCTION
    - export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY_PRODUCTION
    - export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY_PRODUCTION
    - rancher-compose -p dfs up --force-upgrade -c --batch-size 1 -d --upgrade --pull tag-manager
  environment:
    name: production
  only:
    - master
  when: manual
